---
version: '2.4'
services:
  mingler-db-0:
    image: mongo:4.0.0
    container_name: mingler-db-0
    command: --replSet "rs0"
    ports:
      - 27017:27017
    mem_limit: 256m
  mingler-db-1:
    image: mongo:4.0.0
    container_name: mingler-db-1
    command: --replSet "rs0"
    ports:
      - 27018:27017
    mem_limit: 256m
  mingler-db-2:
    image: mongo:4.0.0
    container_name: mingler-db-2
    command: --replSet "rs0"
    ports:
      - 27019:27017
    mem_limit: 256m
